name: Setup Private Git Dependencies
description: Setup Private Git Dependencies
author: EGZOTech

inputs:
  dependencies:
    description: |-
      Private dependencies which will be added to Git in format:
        org/repo:base64
        privkey:base64
        org/repo:base64
        privkey:base64
        ...
    required: true
  export-script:
    description: |-
      Exports a script file with specified name which can be used for accessing
      dependencies in Dockerfile. Dependencies are passed to the script through
      DEPENDENCIES environment variable.
    required: false
  export-only:
    description: |-
      Only does the export-script
    required: false
  custom-prepare:
    description: |-
      Custom shell script which will be executed before installing dependencies
    required: false
  custom-cleanup:
    description: |-
      Custom shell script which will be executed after installing dependencies
    required: false
runs:
  using: "node12"
  main: "dist/index.js"
  post: "dist/index.js"
